# -*- coding: utf-8 -*-
"""Module01_Ex_PartA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qg8VbLU_ROZgD-XAoH0VFou74tP7-lEF?usp=sharing
**Module 01 Exercise: Python Part A**  
**Andy Ortiz**  
**eao7r**

1) Prompt user for:   First name, Last name,  and Age.
"""

print('Enter your first name:')
fname = input()
print('Enter your last name:')
lname = input()
print('Enter your age in years:')
age = input()

"""2) After fetching First name, Last name, and Age, eliminate any whitespace from  
either the left-hand side or the right-hand side.
"""

# trim whitespace from both sides
fname = fname.strip()
lname = lname.strip()
age = age.strip()

"""3) Concatenate the First name and the Last name into a single string  
so it looks like “Last-First” (with a dash separating the last and first names).
"""

fullname = lname + "-" + fname
print(fullname)

"""4) Create a dictionary and add this information to it where the  
name (“Last-First”) is the key and the age (an integer) is the value.
"""

people = {fullname: int(age)}
print(people)

"""5) Simulate gathering information for four people. Your program  
should add each person’s information to the dictionary as described.
"""

print("Now let's create a list of four people")
# reset the input variables
fname = ""
lname = ""
fullname = ""
age = ""

# initialize the dictionary
people = {}

# put all of above code into a loop
# initialize the counter
ctr = 1
while ctr < 5:
  print('Enter your first name:')
  fname = input()
  print('Enter your last name:')
  lname = input()
  print('Enter your age in years:')
  age = input()
  fname = fname.strip()
  lname = lname.strip()
  age = age.strip()
  fullname = lname + "-" + fname
  people[fullname] = age
  print("Your people list:", people)
  ctr = ctr + 1

"""6) Print out the dictionary to a simple text file (e.g., “myOutput.txt”). """

with open("myOutput.txt", 'w') as f: 
  for key, value in people.items(): 
    f.write('%s:%s\n' % (key, value))
f.close()